#!/bin/bash
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
. $SCRIPTPATH/config
curl -s -S https://api.telegram.org/bot$BOT_TOKEN/sendMessage?text="$*"\&chat_id=$USER_ID > /dev/null
